name: "Release Notes Teams Message"
description: "Posts release notes to Teams"
inputs:
  webhook-url:
    description: "Incoming webhook URL"
    required: true
  product-name:
    description: "Product Name"
    required: true
  github-token:
    description: "Github Token"
    required: true
runs:
  using: "node16"
  main: "index.js"
