name: "Release Notes Teams Message"
description: "Posts release notes to Teams"
inputs:
  webhook-url:
    description: "Incoming webhook URL"
    required: true
  product-name:
    description: "Product Name"
    required: true
  linear-url:
    description: "Linear URL"
    required: false
  github-token:
    description: "Github Token"
    required: true
  tag:
    description: "Tag to generate release notes from"
    required: true
  tag-format:
    description: "Format for the release tag (e.g. '{tag}-release')"
    required: false
    default: "{tag}-release"
runs:
  using: "node16"
  main: "dist/index.js"
